server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_platform
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: movie-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
