server:
  port: 8081

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_platform
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true



